# Generated by Django 4.2.7 on 2025-11-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("informacao", "Informação"),
                            ("tarefa", "Tarefa"),
                            ("material", "Material de Apoio"),
                            ("aviso", "Aviso"),
                        ],
                        default="informacao",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True,
                        help_text="Opcional - para tarefas com prazo",
                        null=True,
                        verbose_name="Data de Entrega",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="atividades/",
                        verbose_name="Arquivo Anexo",
                    ),
                ),
                (
                    "fixado",
                    models.BooleanField(
                        default=False,
                        help_text="Atividades fixadas aparecem primeiro",
                        verbose_name="Fixar no Topo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "professor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="core.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["-fixado", "-criado_em"],
            },
        ),
    ]
